services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    networks:
      - my-network
    environment:
      USERS_SERVICE_URL: ${USERS_SERVICE_URL}
      TEAMS_SERVICE_URL: ${TEAMS_SERVICE_URL}
      API_PORT: ${API_PORT}
    ports:
      - "${API_PORT}:5000"

networks:
  my-network:
    driver: bridge
    external: true
