services:
  pokeapi-app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokeapi_service
    restart: always
    ports:
      - "${API_PORT}:6000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - btp-network

networks: 
  btp-network:
    driver: bridge
    external: true