ALTER TABLE users
ADD COLUMN IF NOT EXISTS createdAt TIMESTAMPTZ;

UPDATE users
SET createdAt = NOW()
WHERE createdAt IS NULL;

ALTER TABLE users
ALTER COLUMN createdAt SET DEFAULT NOW();

ALTER TABLE users
ALTER COLUMN createdAt SET NOT NULL;
