ALTER TABLE teams
ADD COLUMN IF NOT EXISTS isFavorite BOOLEAN;

UPDATE teams
SET isFavorite = FALSE
WHERE isFavorite IS NULL;

ALTER TABLE teams
ALTER COLUMN isFavorite SET DEFAULT FALSE;

ALTER TABLE teams
ALTER COLUMN isFavorite SET NOT NULL;
