ALTER TABLE teams
ADD COLUMN IF NOT EXISTS createdAt TIMESTAMPTZ;

UPDATE teams
SET createdAt = NOW()
WHERE createdAt IS NULL;

ALTER TABLE teams
ALTER COLUMN createdAt SET DEFAULT NOW();

ALTER TABLE teams
ALTER COLUMN createdAt SET NOT NULL;
