services:
  user-app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    ports:
      - "${API_PORT}:5555"
    networks:
      - my-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: user_pgdb
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - my-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: user_pgadmin4
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my-network
    depends_on:
      - db

volumes:
  local_pgdata:
  pgadmin-data:

networks: 
  my-network:
    driver: bridge
    external: true